#!/bin/zsh
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

. ~/.config/shell/interactive

###################
# Basic Settings  #
###################

# Terminal settings
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return
stty stop undef # Disable ctrl-s to freeze terminal.

# Load colors
autoload -U colors && colors

# Directory navigation
setopt autocd   # Automatically cd into typed directory.

###################
# History Config  #
###################

export HISTFILE="$XDG_CACHE_HOME/zsh/history"
setopt SHARE_HISTORY        # Share history between sessions
setopt EXTENDED_HISTORY     # Add timestamps to history
setopt HIST_IGNORE_ALL_DUPS # No duplicate commands in history
alias history='history 0'   # Show full history

###################
# Completion      #
###################

# Initialize completion system
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # Include hidden files

###################
# Vi Mode Config  #
###################

# Enable vi mode
bindkey -v
export KEYTIMEOUT=1

# Vi navigation in completion menu
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Cursor shape for different vi modes
function zle-keymap-select {
    case ${KEYMAP} in
        vicmd|block)
            echo -ne '\e[1 q';;
        main|viins|beam|'')
            echo -ne '\e[5 q';;
    esac
}
zle -N zle-keymap-select

function zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}
zle -N zle-line-init

# Set beam shape cursor for new prompts
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q'; }

###################
# Key Bindings    #
###################

# Directory navigation with lf (ctrl-o)
lfcd() {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp" >/dev/null
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'

# Quick access bindings
bindkey -s '^a' 'bc -l\n'                              # Calculator (ctrl-a)
bindkey -s '^f' 'cd "$(dirname "$(fzf)")"\n'          # Fuzzy finder (ctrl-f)
bindkey '^[[P' delete-char                            # Delete key

# Edit command in vim (ctrl-e)
autoload edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

###################
# External Tools  #
###################

# Initialize external tools
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

###################
# Plugins         #
###################

# Load syntax highlighting and other plugins (should be last)
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-extract/extract.plugin.zsh
