#!/bin/bash

# =============================================================================
# Interactive Shell Configuration
# =============================================================================

# Source additional configuration files
# -----------------------------------------------------------------------------
# Load aliases and shortcuts if they exist
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"

# Terminal-specific settings
# -----------------------------------------------------------------------------
if [ -t 0 ]; then
	# Disable messaging from other users by default
	mesg n
	# enable colours
	# if [ $(tput colors) -ge 8 ]; then
	# fi
fi

# Shell Safety Settings
# -----------------------------------------------------------------------------
# Prevent overwriting existing files with redirection
set -C
