#!/bin/sh

alias \
	ls='ls -Alh --color=always' \
	em='emacsclient -nc' \
	emdi="emacsclient -c -a '' --eval '(dired nil)'" \
	br='broot -dp' \
	mv='mv -i' \
	rm='rm -i' \
	config='/usr/bin/git --git-dir=$HOME/.config/dotFiles --work-tree=$HOME' \
	history='history 0' \
	funk='pacmd set-default-sink alsa_output.usb-Logitech_G533_Gaming_Headset-00.analog-stereo' \
	startx='startx "$XDG_CONFIG_HOME/X11/xinitrc" -- "$XDG_CONFIG_HOME/X11/xserverrc" vt1' \
	mirror-update='sudo reflector -c Germany -a 12 -p https -p http --sort rate --save /etc/pacman.d/mirrorlist'
